"""empty message

Revision ID: 0066c5be53b9
Revises: 4c49470bda85
Create Date: 2026-04-16 18:45:02.412364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0066c5be53b9'
down_revision = '4c49470bda85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.Column('tipo_emisor', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['editorial_id'], ['editorial.id'], ),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    # ### end Alembic commands ###
