"""empty message

Revision ID: 056e155b860f
Revises: b428d806ecb6
Create Date: 2026-03-24 17:00:50.540626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056e155b860f'
down_revision = 'b428d806ecb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros_favoritos')
    # ### end Alembic commands ###
