"""empty message

Revision ID: 086fa0786b81
Revises: 1d7cc8b62ae0
Create Date: 2026-04-04 00:14:20.567158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086fa0786b81'
down_revision = '1d7cc8b62ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
