"""Reset y LecturaActual

Revision ID: 151054b00afd
Revises: 
Create Date: 2026-03-31 20:06:09.182382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151054b00afd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lectura_actual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectura_actual')
    op.drop_table('admin')
    # ### end Alembic commands ###
