"""empty message

Revision ID: 16015fbc410d
Revises: bf36d24bf794
Create Date: 2026-04-08 01:15:32.077380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16015fbc410d'
down_revision = 'bf36d24bf794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
