"""Añadidas coordenadas a Editorial

Revision ID: 194299b76113
Revises: 18bb1f18e9be
Create Date: 2026-04-17 22:49:27.452300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194299b76113'
down_revision = '18bb1f18e9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
