"""empty message

Revision ID: 1bf141baf96f
Revises: 769368108ed3
Create Date: 2026-04-08 14:36:46.253730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf141baf96f'
down_revision = '769368108ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
