"""empty message

Revision ID: 3728835b8c05
Revises: 16015fbc410d
Create Date: 2026-04-08 04:22:08.466115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3728835b8c05'
down_revision = '16015fbc410d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
