"""empty message

Revision ID: 4e3243c22051
Revises: 1bf141baf96f
Create Date: 2026-04-10 22:39:58.548555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3243c22051'
down_revision = '1bf141baf96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### Modificación manual para evitar el error de IntegrityError ###
    
    # 1. Cambios en la tabla 'autor' (esto estaba bien)
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=True)

    # 2. Cambios en la tabla 'editorial' (AQUÍ ESTÁ EL TRUCO)
    # Primero agregamos la columna permitiendo NULL
    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        
    # Llenamos las editoriales existentes con False (evita el error de NOT NULL)
    op.execute("UPDATE editorial SET is_verified = False")
    
    # Ahora que no hay NULLs, aplicamos el NOT NULL y los otros cambios
    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.alter_column('is_verified', nullable=False) # Ahora sí podemos ponerlo en False
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # 3. Cambios en la tabla 'libro' (esto estaba bien)
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumen_ia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('resumen_ia')

    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
