"""empty message

Revision ID: 59122c069b79
Revises: a7cc159dd8f7
Create Date: 2026-04-01 02:01:30.963282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59122c069b79'
down_revision = 'a7cc159dd8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['editorial_id'], ['editorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_editorial')
    # ### end Alembic commands ###
