"""empty message

Revision ID: 63e4c6319fbe
Revises: 0f09e167a96c
Create Date: 2026-03-29 23:05:09.403705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e4c6319fbe'
down_revision = '0f09e167a96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['editorial_id'], ['editorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_editorial')
    # ### end Alembic commands ###
