"""add new models

Revision ID: 677131df71df
Revises: 6783e8733e25
Create Date: 2026-05-21 12:01:39.946807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677131df71df'
down_revision = '6783e8733e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generos', sa.String(length=255), nullable=True))

    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sitio_web', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generos_favoritos', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.drop_column('generos_favoritos')
        batch_op.drop_column('biografia')

    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.drop_column('sitio_web')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('generos')
        batch_op.drop_column('biografia')

    # ### end Alembic commands ###
