"""empty message

Revision ID: 6ae3a85e4c92
Revises: 056e155b860f
Create Date: 2026-03-25 22:40:22.345778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae3a85e4c92'
down_revision = '056e155b860f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lector__autores__favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguidor',
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['seguido_id'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('lector_id', 'seguido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidor')
    op.drop_table('lector__autores__favoritos')
    # ### end Alembic commands ###
