"""empty message

Revision ID: 6e168ba75eef
Revises: a89af21288d6
Create Date: 2026-04-06 23:16:24.703566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e168ba75eef'
down_revision = 'a89af21288d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('isbn_13', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])
        batch_op.create_unique_constraint(None, ['isbn_13'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('isbn_13')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
