"""empty message

Revision ID: 7cb348dce40e
Revises: 
Create Date: 2026-04-11 23:27:14.925715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb348dce40e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editorial', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
