"""empty message

Revision ID: 8958e905149d
Revises: 6ae3a85e4c92
Create Date: 2026-03-26 04:26:19.296806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8958e905149d'
down_revision = '6ae3a85e4c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_lector_seguido_uc', ['lector_id', 'seguido_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguidor', schema=None) as batch_op:
        batch_op.drop_constraint('_lector_seguido_uc', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
