"""reset_migrations

Revision ID: 94f34bb7db8c
Revises: 
Create Date: 2026-03-27 22:18:47.782261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f34bb7db8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['seguido_id'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lector_id', 'seguido_id', name='_lector_seguido_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidor')
    # ### end Alembic commands ###
