"""empty message

Revision ID: a978def4ae9d
Revises: 63e4c6319fbe
Create Date: 2026-03-29 23:29:59.667444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a978def4ae9d'
down_revision = '63e4c6319fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_editorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_editorial', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
