"""empty message

Revision ID: b428d806ecb6
Revises: ec1a3755f89f
Create Date: 2026-03-24 05:00:20.514134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b428d806ecb6'
down_revision = 'ec1a3755f89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editorial_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('libro_lector_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'editorial', ['editorial_id'], ['id'])
        batch_op.drop_column('lector_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lector_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('libro_lector_id_fkey'), 'lector', ['lector_id'], ['id'])
        batch_op.drop_column('editorial_id')

    # ### end Alembic commands ###
