"""campos opcionales para registro rapido

Revision ID: dcac889dc18d
Revises: 
Create Date: 2026-04-17 22:28:20.980261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcac889dc18d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('pais_donde_reside',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.alter_column('pais_donde_reside',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
