"""Sync 2.0: Comentarios y PostLector

Revision ID: e429c796036c
Revises: 
Create Date: 2026-05-05 15:32:10.839214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e429c796036c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_lector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('lector_id', sa.Integer(), nullable=True),
    sa.Column('editorial_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('post_editorial_id', sa.Integer(), nullable=True),
    sa.Column('post_autor_id', sa.Integer(), nullable=True),
    sa.Column('post_lector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['editorial_id'], ['editorial.id'], ),
    sa.ForeignKeyConstraint(['lector_id'], ['lector.id'], ),
    sa.ForeignKeyConstraint(['post_autor_id'], ['post_autor.id'], ),
    sa.ForeignKeyConstraint(['post_editorial_id'], ['post_editorial.id'], ),
    sa.ForeignKeyConstraint(['post_lector_id'], ['post_lector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('pais_donde_reside',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lector', schema=None) as batch_op:
        batch_op.alter_column('pais_donde_reside',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    op.drop_table('comentario')
    op.drop_table('post_lector')
    # ### end Alembic commands ###
